version: '3'

services:
  vscode:
    build:
      context: ..
      args:
        - VARIANT=${NODE_VERSION:-16}-${OS_VERSION:-bullseye}
        - FLAVOUR=${BASE_LANGUAGE:-javascript}
      dockerfile: .devcontainer/Dockerfile.devcontainer
    init: true
    container_name: ${COMPOSE_PROJECT_NAME:-workspace}-vscode
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_DEFAULT_REGION
    command: sleep infinity
    networks:
      - default
    volumes:
      - ..:/workspace
      - ~/.ssh:/root/.ssh
      - /var/run/docker.sock:/var/run/docker.sock
      - vscode-extensions:/root/.vscode-server/extensions

volumes:
  vscode-extensions:
    external: true

networks:
  default:
    name: ${COMPOSE_PROJECT_NAME:-workspace}-net
